# Site settings
title: Ahmed Khalifa | Threat Researcher
description: Doing Threat Research, Hunting Adversaries Infrastructure 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "https://github.com/kh4lifa0x/about_me/edit/master" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ahmed Khalifa
user_description: Threat Researcher and DFIR Engineer specializing in infrastructure adversary hunting and forensic investigations. I have a strong passion for malware analysis and uncovering advanced threat actor techniques.
user_title: Threat Researcher
email: ahmedkhalifa9@proton.me
twitter_username: svchostss_exe
github_username:  kh4lifa0x
gplus_username:  kh4lifa0x

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
